name: CI

on:
  workflow_dispatch:
  push:
    branches: master
    paths-ignore: 'bench/**'
  pull_request:
    branches: master
    paths-ignore: 'bench/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Run static checks
        run: npm run lint
      - name: Build
        run: npm run build
      - name: Save the build
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build
    
  test:
    needs: build
    strategy:
      matrix:
        os: [windows-latest, macOS-latest, ubuntu-latest]
        node: [8, 10, 12, 14]        
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Install the dependencies using the package manager whose lock file is in the root dir
        uses: jaid/action-npm-install@v1.2.1
      - name: Download the build
        uses: actions/download-artifact@v2
        with:
          name: build
      - name: Test
        run: npm run test
        
  ci:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Skip
        run: exit 0
