name: Publish
on: [workflow_dispatch]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '10.x'
          registry-url: 'https://npm.pkg.github.com'
      - run: sed -i 's/"name":\s*"/a ${{ github.repository_owner }}/' package.json
      - run: npm install      
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
