name: Publish to GPR

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ job.runs-on }}
      - run: echo ${{ job.container.runs-on }}
      - run: echo ${{ job.container }}
      - name: Wait for the CI workflow to complete
        id: wait-for-ci
        uses: fountainhead/action-wait-for-check@v1.0.0        
        with:
          checkName: ci (14, ubuntu-latest)
          token: ${{ secrets.GITHUB_TOKEN }}
      - if: steps.wait-for-ci.outputs.conclusion == 'failure'
        run: exit 1        
      - name: Check out the repository
        uses: actions/checkout@v2
        with:
          ref: master
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: https://npm.pkg.github.com
      - name: Add the repository owner as the scope to the package name
        run: sed -i -r 's/("name":\s*")([^@])/\1@${{ github.repository_owner }}\/\2/' package.json
      - name: Install the dependencies using the package manager whose lock file is in the root dir
        uses: jaid/action-npm-install@v1.2.1
      - name: Publish the package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
