name: Publish

on:
  workflow_dispatch:
  push:
    tags: "v*.*.*"

jobs:
  publish:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Wait for the CI workflow to complete
        id: wait-for-ci
        uses: fountainhead/action-wait-for-check@v1.0.0
        with:
          checkName: ci
          token: ${{ secrets.GITHUB_TOKEN }}
      - if: steps.wait-for-ci.outputs.conclusion == 'failure'
        run: exit 1
      - name: Check out the repository
        uses: actions/checkout@v2
        with:
          ref: master
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Download the build
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ci.yml
          name: build
          commit: ${{ github.sha }}
      - name: Make the package publishable
        run: npx json -I -f package.json -e "delete this.private"
      - name: Publish to NPM
        run: npm publish
      - name: Add the repository owner as the scope and set the registry to GPR
        run: 'npx json -I -f package.json -e "this.name[0] !== ''@'' && (this.name = ''@${{ github.repository_owner }}/'' + this.name); this.publishConfig = {''registry'': ''https://npm.pkg.github.com''}"'
      - name: Install the dependencies using the package manager whose lock file is in the root dir
        uses: jaid/action-npm-install@v1.2.1
      - name: Publish the package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
