name: Release
on: 
  push:
    branches:
      - master
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: lewagon/wait-on-check-action@v0.1-beta.2
        with:
          check-name: ci
          wait-interval: 10
          ref: ${{ github.sha }}          
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v2
