name: Release
on: 
  push:
    branches:
      - master
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: lewagon/wait-on-check-action@v0.1-beta.2
        with:
          check-name: CI
          ref: master
          wait-interval: 10           
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v2
