name: Create a GitHub Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:      
      - name: Wait for the CI workflow to complete
        uses: fountainhead/action-wait-for-check@v1.0.0
        id: wait-for-ci
        with:
          checkName: ci (14, ubuntu-latest)
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: exit 1
        if: steps.wait-for-ci.outputs.conclusion == 'failure'
      - name: Check out the repository
        uses: actions/checkout@v2
        with:
          ref: master
      - name: Create a GitHub release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
